name = "Places Pack"
author = "faggot family"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ca2d9889be58f5e447e7c875ac84f52a4b9b8297a04244424bc94380cf0b22b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[options]
acceptable-game-versions = []
