name = "Places Pack"
author = "faggot family"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47a29692b99dc8d852be48dc157feee3a58bcb0c38b2207760f362ee10bdc4d5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[options]
acceptable-game-versions = []
