name = "Places Pack"
author = "faggot family"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39cbf9518dc72be0db79a4329746dbeabee8163b11dd193d40ae402e6a084d59"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[options]
acceptable-game-versions = []
